### ISSUE TITLE
Windows Phone Internals can't find RM-1105 FFU and recovery files

### ISSUE THREAD

**Issue by thanone2** [ReneLergner/WPinternals#89]
### Description

I tried using RM-1104 files, but it didn't work, and it's giving me: "Error 0x1304: Invalid platform ID"
and also, I forgot to check the phone after resetting it, but when I boot into W10M it doesn't show any thing other than the navigation bar, battery icon, and the no sim card icon, I can turn it off, it takes screen shots, but that's about it.

### Expected behavior

I expected it to not fail, but, idk what else to put here

### WPinternals Version

Latest version (date it was published: 12/23/2024)

### Windows Version

Windows 11 Pro 24H2 26100.2894

### Phone model

Lumia 950 AT&T

### Relevant Assets

[WPInternals.log](https://github.com/user-attachments/files/18581790/WPInternals.log)

**Comment by thanone2** [comment]
oh, and windows device recovery app throws an error about proxy settings, I reinstalled it then it tells me to get the newest version of the app, which it is the newest version

**Comment by thanone2** [comment]
there's only this, and it won't download it

![Image](https://github.com/user-attachments/assets/04de712d-74d7-4d14-b520-4324cb15be88)

**Comment by thanone2** [comment]
I just did a hard factory reset, I'm gonna see what happens

**Comment by thanone2** [comment]
ok, so resetting got me back to windows mobile working fine

**Comment by thanone2** [comment]
wdym "not planned"?

**Comment by gus33000** [comment]
Sorry there is only two choices on github; complete and "not planned" Given your issue is resolved and it wasnt exactly about this program, thats why it got closed

**Comment by thanone2** [comment]
it's not resolved though, there is still no ffu for my lumia

**Comment by thanone2** [comment]
I fixed the other problem I had, yeah, but the original problem still stands for me

**Comment by thanone2** [comment]
I need the RM-1105 FFU for my phone and it's not giving me it... idk what to do @gus33000

**Comment by gus33000** [comment]
Microsoft permanently shutdown the servers that hosted these files. That's why the program doesn't give anything to you. There's nothing we can do and it's not an issue with the program. You can search online for third party sites that would rehost those. (Like Lumia firmware). But there's no issue with this tool. This issue remains closed.

**Comment by thanone2** [comment]
dang, ok, thanks
